//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGDeckBuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTB
    {
        public int CardId { get; set; }
        public Nullable<int> DeckId { get; set; }
        public string CardValue { get; set; }
    }
}
