//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGDeckBuilder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomCardTB
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "A Card Name is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "A Card Text/Description is Required")]
        public string Description { get; set; }
        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "The Cards's Power is Required and It Must be a Number")]
        public string Power { get; set; }
        [Required]
        [RegularExpression("^[0-9]*$", ErrorMessage = "The Cards's Power is Required and It Must be a Number")]
        public string Tough { get; set; }
        [Required(ErrorMessage = "A URL Image Link is Required")]
        public string Image { get; set; }
        public int PlayerId { get; set; }
    }

}
